#!/usr/bin/env python3
"""Give every page in this repo the Copilot favicon.

The tab icon matched nothing before, so browsers fell back to the generic
globe. This mirrors the Copilot-in-1mins portal, which serves copilot-logo.png
as its icon, but inlines a downscaled copy as a data URI instead of linking the
file: half of these pages (the agent map, the agent builder, the newsletters,
the offline site editions) are handed around as standalone files, and a
relative href breaks the moment one of them is saved somewhere else.

Idempotent: running it again refreshes the tag rather than stacking copies.

Usage:  python _tools/add_favicon.py [--check]
"""

from __future__ import annotations

import base64
import io
import re
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE_LOGO = ROOT / "copilot-logo.png"
ICON_PX = 48

MARKER = "<!-- FAVICON v1 -->"
TAG_RE = re.compile(r"[ \t]*<!-- FAVICON v1 -->.*?\r?\n", re.S)
# Most pages open with <meta charset>, but a few of the newsletters are XHTML
# email templates that declare the encoding with http-equiv instead.
ANCHORS = (
    re.compile(r"([ \t]*<meta charset=[^>]*>[ \t]*\r?\n)", re.I),
    re.compile(r"([ \t]*<meta http-equiv=\"Content-Type\"[^>]*>[ \t]*\r?\n)", re.I),
    re.compile(r"([ \t]*<head[^>]*>[ \t]*\r?\n)", re.I),
)
ICON_LINK_RE = re.compile(r"[ \t]*<link rel=\"icon\"[^>]*>[ \t]*\r?\n")
# downloads/ is generated by build_offline.py, which inlines its own tag.
# school/ is maintained separately and is deliberately left alone.
SKIP_DIRS = {"downloads", "school", ".git", "_tools", "vendor"}


def favicon_tag() -> str:
    im = Image.open(SOURCE_LOGO).convert("RGBA").resize((ICON_PX, ICON_PX), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True)
    uri = "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")
    return MARKER + "\n" + '<link rel="icon" type="image/png" sizes="any" href="' + uri + '" />\n'


def pages() -> list[Path]:
    return [
        p for p in sorted(ROOT.rglob("*.html"))
        if not SKIP_DIRS & set(p.relative_to(ROOT).parts)
    ]


def apply(path: Path, tag: str) -> bool:
    html = path.read_text(encoding="utf-8")
    stripped = ICON_LINK_RE.sub("", TAG_RE.sub("", html))

    for anchor in ANCHORS:
        updated, n = anchor.subn(lambda m: m.group(1) + tag, stripped, count=1)
        if n:
            break
    else:
        n = 0
    if not n:
        raise SystemExit(f"{path}: found no <head> or <meta> to anchor the favicon to")
    if updated == html:
        return False
    path.write_text(updated, encoding="utf-8", newline="")
    return True


def main() -> int:
    tag = favicon_tag()
    targets = pages()

    if "--check" in sys.argv:
        missing = [p for p in targets if MARKER not in p.read_text(encoding="utf-8")]
        for p in missing:
            print("missing: " + p.relative_to(ROOT).as_posix())
        print(f"{len(targets) - len(missing)}/{len(targets)} pages carry the favicon")
        return 1 if missing else 0

    changed = sum(apply(p, tag) for p in targets)
    print(f"favicon applied: {changed} changed, {len(targets)} pages total")
    return 0


if __name__ == "__main__":
    sys.exit(main())